export const Types = {
    GET_DETAIL: 'GET_DETAIL',
    UPDATE_USER_DETAIL: 'UPDATE_USER_DETAIL',
    NEW_ADDRESS: 'NEW_ADDRESS',
    EDIT_ADDRESS: 'EDIT_ADDRESS',
    ALL_ADDRESSES: 'ALL_ADDRESSES',
}
