export const Types = {
  GET_ITEM: 'GET_ITEM',
  GET_DETAIL: 'GET_DETAIL',
  UPDATE_ITEM: 'UPDATE_ITEM',
  NEW_ITEM: 'NEW_ITEM',
  ALL_ITEMS: 'ALL_ITEMS',
  DELETE_ITEM: 'DELETE_ITEM',
  ALL_TAGS: 'ALL_TAGS',
  ITEMS_BASED_ON_TAGS: 'ITEMS_BASED_ON_TAGS'
}
