export const Types = {
  VIEW_CART: 'VIEW_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  INCREASE_ITEM_QTY: 'INCREASE_ITEM_QTY',
  CLEAR_CART: 'CLEAR_CART'
}
