export const Types = {
  GET_CATEGORY: 'GET_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  NEW_CATEGORY: 'NEW_CATEGORY',
  ALL_CATEGORIES: 'ALL_CATEGORIES',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  LANDING_CATEGORIES: 'LANDING_CATEGORIES',
  LANDING_ITEMS: 'LANDING_ITEMS',
  ITEM_DETAIL: 'ITEM_DETAIL'
}
