export const Types = {
  GET_PICKUP_STATION: 'GET_PICKUP_STATION',
  UPDATE_PICKUP_STATION: 'UPDATE_PICKUP_STATION',
  NEW_PICKUP_STATION: 'NEW_PICKUP_STATION',
  ALL_PICKUP_STATIONS: 'ALL_PICKUP_STATIONS',
  DELETE_PICKUP_STATION: 'DELETE_PICKUP_STATION',

  GET_CUSTOMER_PICKUP_LOCATION: 'GET_CUSTOMER_PICKUP_LOCATION'
}
